# Generated by Django 5.0.1 on 2025-04-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_event_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('event_start_date', models.DateTimeField()),
                ('event_end_date', models.DateTimeField()),
                ('sell_from', models.DateTimeField()),
                ('sell_to', models.DateTimeField()),
                ('sold_out', models.BooleanField()),
                ('zone_id', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('name', models.CharField(max_length=100)),
                ('numbered', models.BooleanField()),
            ],
        ),
    ]
