# Generated by Django 5.0.1 on 2025-04-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sell_mode',
            field=models.CharField(default='online', max_length=50),
        ),
    ]
