# Generated by Django 5.0.1 on 2025-04-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_sell_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
